name: godot-ci export
on:
  push:
    tags:
      - 'v*.*.*'

env:
  GODOT_VERSION: 3.4.2
  EXPORT_NAME: godot-wordle

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Install rsync ðŸ“š
        run: |
          apt-get update && apt-get install -y rsync
      - name: Windows Build
        run: |
          mkdir ./${EXPORT_NAME}
          rsync -Rr . ./${EXPORT_NAME}
          mkdir -v -p build/windows
          cd ${EXPORT_NAME}
          godot -v --export "Windows Desktop" ../build/windows/${EXPORT_NAME}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows.${{ github.ref_name }}
          path: build/windows
      - name: Butler Upload
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: godot-wordle
          ITCH_USER: brawmario
          PACKAGE: build/windows
          VERSION: ${{ github.ref_name }}

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Install rsync ðŸ“š
        run: |
          apt-get update && apt-get install -y rsync
      - name: Linux Build
        run: |
          mkdir ./${EXPORT_NAME}
          rsync -Rr . ./${EXPORT_NAME}
          mkdir -v -p build/linux
          cd ${EXPORT_NAME}
          godot -v --export "Linux/X11" ../build/linux/${EXPORT_NAME}.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux.${{ github.ref_name }}
          path: build/linux
      - name: Butler Upload
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: godot-wordle
          ITCH_USER: brawmario
          PACKAGE: build/linux
          VERSION: ${{ github.ref_name }}

  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Install rsync ðŸ“š
        run: |
          apt-get update && apt-get install -y rsync
      - name: Web Build
        run: |
          mkdir ./${EXPORT_NAME}
          rsync -Rr . ./${EXPORT_NAME}
          mkdir -v -p build/web
          cd ${EXPORT_NAME}
          godot -v --export "HTML5" ../build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web.${{ github.ref_name }}
          path: build/web
      - name: Butler Upload
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: web
          ITCH_GAME: godot-wordle
          ITCH_USER: brawmario
          PACKAGE: build/web
          VERSION: ${{ github.ref_name }}
      - name: Deploy to GitHub Pages ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: build/web

  export-mac:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Install rsync ðŸ“š
        run: |
          apt-get update && apt-get install -y rsync
      - name: Mac Build
        run: |
          mkdir ./${EXPORT_NAME}
          rsync -Rr . ./${EXPORT_NAME}
          mkdir -v -p build/mac
          cd ${EXPORT_NAME}
          godot -v --export "Mac OSX" ../build/mac/${EXPORT_NAME}.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: mac.${{ github.ref_name }}
          path: build/mac
      - name: Butler Upload
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: mac
          ITCH_GAME: godot-wordle
          ITCH_USER: brawmario
          PACKAGE: build/mac
          VERSION: ${{ github.ref_name }}
