name: Godot CI
on:
  push:
    tags:
      - 'v*'

env:
  GAME_NAME: godot-wordle

jobs:
  export-game:
    name: Export game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Export
        id: export
        uses: firebelley/godot-export@v4.7.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./
          use_godot_4: true
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.windows
          path: ${{ steps.export.outputs.build_directory }}/Windows Desktop
      - name: Upload MacOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.mac
          path: ${{ steps.export.outputs.build_directory }}/macOS
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.linux
          path: ${{ steps.export.outputs.build_directory }}/LinuxX11
      - name: Upload Web Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.web
          path: ${{ steps.export.outputs.build_directory }}/Web

  itch-io-upload:
    name: Upload to Itch.io
    needs: export-game
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, mac, linux, web]
    steps:
      - name: Download Artifact (${{ matrix.platform }})
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.${{ matrix.platform }}
      - name: Butler Upload
        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.platform }}
          ITCH_GAME: ${{ env.GAME_NAME }}
          ITCH_USER: brawmario
          PACKAGE: .
          VERSION: ${{ github.ref_name }}

  pages-deploy:
    name: Deploy to GitHub Pages
    needs: export-game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Artifact (web)
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.GAME_NAME }}.${{ github.ref_name }}.web
          path: export/web
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: export/web