name: godot-ci export
on:
  push:
#    tags:
#      - 'v*.*.*'

env:
  GODOT_VERSION: 4.0

jobs:
  export-game:
    name: Export game to ${{ matrix.PLATFORM }}
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.0
    strategy:
      matrix:
        include:
          - PLATFORM: windows
            EXPORT_PRESET: Windows Desktop
            EXPORT_FILENAME: godot-wordle.exe
          - PLATFORM: linux
            EXPORT_PRESET: Linux/X11
            EXPORT_FILENAME: godot-wordle.x86_64
          - PLATFORM: mac
            EXPORT_PRESET: Mac OSX
            EXPORT_FILENAME: godot-wordle.zip
          - PLATFORM: web
            EXPORT_PRESET: HTML5
            EXPORT_FILENAME: index.html
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.PLATFORM }}
          godot -v --export "${{ matrix.EXPORT_PRESET }}" build/${{ matrix.PLATFORM }}/${{ matrix.EXPORT_FILENAME }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: godot-wordle.${{ github.ref_name }}.${{ matrix.PLATFORM }}
          path: build/${{ matrix.PLATFORM }}
#      - name: Butler Upload
#        uses: josephbmanley/butler-publish-itchio-action@v1.0.3
#        env:
#          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
#          CHANNEL: ${{ matrix.PLATFORM }}
#          ITCH_GAME: godot-wordle
#          ITCH_USER: brawmario
#          PACKAGE: build/${{ matrix.PLATFORM }}
#          VERSION: ${{ github.ref_name }}
#      - name: Install rsync
#        if: matrix.PLATFORM == 'web'
#        run: |
#          apt-get update && apt-get install -y rsync
#      - name: Deploy to GitHub Pages
#        if: matrix.PLATFORM == 'web'
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          folder: build/web